<%@ Page 
    Language="C#"
    AutoEventWireup="true"
    CodeFile="Workshop in Heaven.aspx.cs"
    Inherits="WordEngineering.Workshop_In_Heaven" 
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Workshop in Heaven</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:ScriptManager ID="ScriptManager1" runat="server" EnablePartialRendering="true" />
    </div>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
                <asp:GridView
                    ID="GridViewWorkshopInHeaven"
                    runat="server"
                    AllowPaging="True"
                    AllowSorting="True"
                    AutoGenerateColumns="False"
                    AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateSelectButton="True"
                    CellPadding="4"
                    DataKeyNames="sequenceOrderId"
                    ForeColor="#333333"
                    GridLines="None"
                    OnPageIndexChanging="GridView_PageIndexChanging"
                    OnRowCancelingEdit="GridView_RowCancelingEdit"
                    OnRowDeleting="GridView_RowDeleting"
                    OnRowEditing="GridView_RowEditing"
                    OnRowUpdated="GridView_RowUpdated"
                    OnSorting="GridView_Sorting"
                    SelectedIndex="0"
                    ShowFooter="True"
                >
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="White" />
                    
                    <Columns>
                        <asp:TemplateField
                            HeaderText="Word"
                            SortExpression="Word"
                        >
                            <ItemTemplate>
                                <asp:Label
                                    Runat="Server"
                                    id="LabelGridViewWorkshopInHeavenItemTemplateWord" 
                                    Text='<%# Eval("Word") %>'
                                />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenEditItemTemplateWord" 
                                    Text='<%# Bind("Word") %>'
                                />
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenFooterTemplateWord"
                                    Text='<%# Bind("Word") %>'
                                />
                            </FooterTemplate>
                        </asp:TemplateField>
						<asp:TemplateField
                            HeaderText="Commentary"
                            SortExpression="Commentary"
                        >
                            <ItemTemplate>
                                <asp:Label
                                    Runat="Server"
                                    id="LabelGridViewWorkshopInHeavenItemTemplateCommentary" 
                                    Text='<%# Eval("Commentary") %>'
                                />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenEditItemTemplateCommentary" 
                                    Text='<%# Bind("Commentary") %>'
                                />
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenFooterTemplateCommentary"
                                    Text='<%# Bind("Commentary") %>'
                                />
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField
                            HeaderText="Dated"
                            SortExpression="Dated"
                        >
                            <ItemTemplate>
                                <asp:Label
                                    Runat="Server"
                                    id="LabelGridViewWorkshopInHeavenItemTemplateDated" 
                                    Text='<%# Eval("Dated", "{0:d}") %>'
                                />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenEditItemTemplateDated" 
                                    Text='<%# Bind("Dated") %>'
                                />
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenFooterTemplateDated"
                                    Text='<%# Bind("Dated") %>'
                                />
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField
                            HeaderText="SequenceOrderId"
                            SortExpression="SequenceOrderId"
                        >
                            <ItemTemplate>
                                <asp:Label
                                    Runat="Server"
                                    id="LabelGridViewWorkshopInHeavenItemTemplateSequenceOrderID" 
                                    Text='<%# Eval("SequenceOrderID") %>'
                                />
                            </ItemTemplate>
<%--
                            <EditItemTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenEditItemTemplateSequenceOrderID" 
                                    Text='<%# Bind("SequenceOrderId") %>'
                                />
                            </EditItemTemplate>
--%>
                            <FooterTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenFooterTemplateSequenceOrderID"
                                    Text='<%# Bind("SequenceOrderID") %>'
                                />
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField
                            HeaderText="URI"
                            SortExpression="URI"
                        >
                            <ItemTemplate>
                                <asp:HyperLink  
                                    Runat="Server"
                                    id="HyperLinkGridViewWorkshopInHeavenItemTemplateURI" 
                                    NavigateUrl='<%# WordEngineering.UtilityScheme.PrefixScheme( Eval("URI") ) %>'
                                    Text='<%# Eval("URI") %>'
                                    Target="_blank"
                                />  
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenEditItemTemplateURI" 
                                    Text='<%# Bind("URI") %>'
                                />
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenFooterTemplateURI"
                                    Text='<%# Bind("URI") %>'
                                />
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField
                            HeaderText="ContactID"
                            SortExpression="ContactID"
                        >
                            <ItemTemplate>
                                <asp:Label
                                    Runat="Server"
                                    id="LabelGridViewWorkshopInHeavenItemTemplateContactID" 
                                    Text='<%# Eval("ContactID") %>'
                                />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenEditItemTemplateContactID" 
                                    Text='<%# Bind("ContactID") %>'
                                />
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenFooterTemplateContactID"
                                    Text='<%# Bind("ContactID") %>'
                                />
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField
                            HeaderText="ScriptureReference"
                            SortExpression="ScriptureReference"
                        >
                            <ItemTemplate>
                                <asp:Label
                                    Runat="Server"
                                    id="LabelGridViewWorkshopInHeavenItemTemplateScriptureReference" 
                                    Text='<%# Eval("ScriptureReference") %>'
                                />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenEditItemTemplateScriptureReference" 
                                    Text='<%# Bind("ScriptureReference") %>'
                                />
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox 
                                    Runat="Server"
                                    id="TextBoxGridViewWorkshopInHeavenFooterTemplateScriptureReference"
                                    Text='<%# Bind("ScriptureReference") %>'
                                />
                                <asp:Button 
                                    Runat="Server"           
                                    ID="ButtonGridViewWorkshopInHeavenFooterTemplateAdd"
                                    OnClick="GridView_Insert"
                                    Text="Add"
                                />
                            </FooterTemplate>
                        </asp:TemplateField>
                     </Columns>
                </asp:GridView>
                <asp:Literal runat="server" ID="Feedback" />
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</body>
</html>